# Uncomment the next line to define a global platform for your project
 platform :ios, '16.4'

target 'poc-integration' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for poc-integration
  flutter_application_path = '../home'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

end

post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
end